### PR TITLE
Add optional session expiration information

### PR DESCRIPTION
**Pull request by dfournier**
Hi,

I'd like add an optional session expiration date. Documentation about that field is available [here](http://www.datypic.com/sc/saml2/a-SessionNotOnOrAfter-1.html). Since it's optional, this PR doesn't break the API.

Best,
David

### CODE REVIEW

**Comment by dfournier** [comment]
@jphenow any chance to get my code reviewed?

**Comment by jphenow** [comment]
Thanks for the code and the bump. Could you add some information in the README and/or the docs? Otherwise will be happy to merge. Will release after I get bearings again a bit. I no longer work at the company I created this from, so it's not at the top of my list

**Comment by dfournier** [comment]
Thanks for your feedback @jphenow.

I changed a bit the behaviour of `session_expiry`. Now it must be an `Integer`, can have a default value from the configuration and the value `0` means the session will never expired.

What do you think of those changes?

If you're happy with this, let me know to squash those 2 commits before merging 😄

**Comment by dfournier** [comment]
@jphenow any chance to get my PR reviewed again?

**Comment by dfournier** [comment]
@jphenow any chance to see this PR merged?

**Pull request merged**
