### PR TITLE
Enable overriding of AuthnContextClassRef in the SamlIdp::Controller.

### PR DESCRIPTION
**Pull request by omb-awong**
This makes sense because the AuthnContextClassRef can change
depending on the authentication level of the user which differs
per request.

### CODE REVIEW

**Comment by amoose** [comment]
+1

**Comment by nateborr** [comment]
+1

**Comment by jphenow** [comment]
Sorry for the late notice guys, I should have been getting email notifications for these. I'll take a look shortly

**Comment by jphenow** [comment]
This has been merged in and released under 0.2.0

**Pull request merged**
