### PR TITLE
fix example X.509 certificate

### PR DESCRIPTION
**Pull request by ccutrer**
SAML (well, xmlsec) expects the certificate itself, without the PEM header/trailer. The current example was double-encoded, and causing failures with xmlsec verifiers that extract the certificate from the SAMLResponse

### CODE REVIEW

**Comment by jphenow** [comment]
Hm the specs are breaking now, though. This could be problematic if the code is expecting as presented in the default and we're now altering it without altering the code that uses the cert.

The bigger problem is that this presents a breaking change - I think we'd need to bump up the major version if we change the code to interpret the cert differently.

**Comment by ccutrer** [comment]
That's the funny thing - the code doesn't do anything with the certificate - it just passes it through. I can update the specs (the signatures won't be affected), but really this is a huge security faux paus - I've come across multiple people using the example certificate in production applications, which means there's absolutely no security. Ideally you would remove an "example" certificate completely and force people to provide their own certificate and private key (you can still include one in the specs - so long as a user of the library doesn't automatically get one without doing anything).

**Comment by jphenow** [comment]
I'm absolutely understanding your security concern. Though, I won't pull
the rug out without an upgrade path, nor with broken tests.

I'll look into the tests and an upgrade path this weekend when I can get
back to a computer, if you aren't able to.

Thank you for starting us on the path, regardless

On Saturday, August 22, 2015, Cody Cutrer <notifications@github.com> wrote:

> That's the funny thing - the code doesn't do anything with the certificate
> - it just passes it through. I can update the specs (the signatures won't
> be affected), but really this is a huge security faux paus - I've come
> across multiple people using the example certificate in production
> applications, which means there's absolutely no security. Ideally you would
> remove an "example" certificate completely and force people to provide
> their own certificate and private key (you can still include one in the
> specs - so long as a user of the library doesn't automatically get one
> without doing anything).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportngin/saml_idp/pull/29#issuecomment-133727742>.
>


-- 
Jon Phenow
Software Engineer
g: http://github.com/jphenow
j.phenow@gmail.com

**Comment by chrisblatchley** [comment]
Just want to say for the record that this did fix a testing issue for me (to be fair I'm not deeply familiar with SAML). I was using the default certs for testing SSO integration with Canvas LMS which uses the response provided cert for fingerprint verification. I will of course use real certificates in production, but it was nice to see a validated login attempt thanks to this issue being made known.

**Comment by jphenow** [comment]
Released under v0.2.1

**Pull request merged**
