### PR TITLE
Let @saml_acs_url be configurable.

### PR DESCRIPTION
**Pull request by ndyakov**
We have a use case were our SP is running on different port in development, so we need to simply add port to the `@saml_acs_url`.

I have also incremented the ruby version as this is working with 2.1.5 as far as we tested it.

### CODE REVIEW

**Comment by ndyakov** [comment]
@jphenow, any updates on that?

**Comment by jphenow** [comment]
Since you include the module you'd be able to override like this:

```ruby
include SamlIdp::Controller

def saml_acs_url
  # your logic
end
```

Yes? Or thoughts on that?

**Comment by ndyakov** [comment]
Actually I think this will do... Sorry about the inconvenience.

**Comment by jphenow** [comment]
No worries! I was trying to think of a more configurable way to do it when I first saw it, then on second look I thought of that. 

If you find another way that you think would support customization better, let me know!

**Pull request closed without merging**
