### PR TITLE
per the SAML spec, the SessionIndex should match the Assertion ID

### PR DESCRIPTION
**Pull request by pkarman**
ref https://docs.oasis-open.org/security/saml/v2.0/sstc-saml-errata-2.0-cd-04.html#2_34_E38__Clarification_Regarding_Index_on_<LogoutRequest>

### CODE REVIEW

**Comment by jphenow** [comment]
Is that what the the docs are saying? At first glance it looked like it was implying that we receive a session index during first authentication statement

**Comment by pkarman** [comment]
I realize that oasis doc is not clearly backing up this change. Here's a better example:
https://www.samltool.com/generic_sso_res.php

note that in all the examples, the SessionIndex attribute value matches its parent Assertion ID attribute value.

Here's another reference: http://www.componentspace.com/Forums/1643/SessionIndex-in-SAML-Response#bm1644

"As per the SAML specification, we use the assertion ID as the session index."

**Comment by pkarman** [comment]
here's what the spec says:

> In general, any string value MAY be used as a SessionIndex value. However, when privacy is a
consideration, care must be taken to ensure that the SessionIndex value does not invalidate other
privacy mechanisms. Accordingly, the value SHOULD NOT be usable to correlate activity by a principal
across different session participants. Two solutions that achieve this goal are provided below and are
RECOMMENDED:
• Use small positive integers (or reoccurring constants in a list) for the SessionIndex. The SAML
authority SHOULD choose the range of values such that the cardinality of any one integer will be
sufficiently high to prevent a particular principal's actions from being correlated across multiple session
participants. The SAML authority SHOULD choose values for SessionIndex randomly from within
this range (except when required to ensure unique values for subsequent statements given to the
same session participant but as part of a distinct session).
• Use the enclosing assertion's ID value in the SessionIndex.

**Comment by jphenow** [comment]
Just to clarify: That first link doesn't appear to reuse the assertion ID as the session index 

your other findings seem fine though; just wanted to make sure we're following the general spec. I've lost a lot of touch with the is spec partly because its somewhat trying to keep it all straight hah.

Cool. I can merge and release this. Would you consider this a bugfix release more than a breaking change or anything?

**Comment by pkarman** [comment]
You are correct; that first link was my error. The attribute values do not match.

I'm following the spec recommendation https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

bugfix, definitely.

**Comment by jphenow** [comment]
`v0.3.2` released

**Pull request merged**
