### PR TITLE
allows the HTTP-Redirect binding for IDP SLO URL

### PR DESCRIPTION
**Pull request by smsohan**
@pkarman This change piggy backs onto https://github.com/sportngin/saml_idp/pull/41 to allow for a redirect binding on the SLO. Please review. If this is ok, I can send another PR bumping up the version for a release.

### CODE REVIEW

**Comment by jphenow** [comment]
Not sure why tests re failing - once we can get those green, I can merge this

**Comment by jphenow** [comment]
Hey sorry about this - would you merge master and push again? Updated gemspec to require 2.2+ and specified gems more specifically so the travis build should be green hopefully. Thanks!

**Comment by wingrunr21** [comment]
@jphenow can this PR be merged? Would be great to have this in the gem.

**Comment by jphenow** [comment]
v0.5.0 has been released

**Comment by wingrunr21** [comment]
👍  thanks!

**Pull request merged**
